# Generated by rust2rpm 27
# * Doesn't compile for testutils
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

%global crate eza

Name:           rust-eza
Version:        0.21.2
Release:        %autorelease
Summary:        Modern replacement for ls

License:        EUPL-1.2
URL:            https://crates.io/crates/eza
Source:         %{crates_source}
Source:         eza-0.21.2-vendor.tar.xz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          eza-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A modern replacement for ls.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.txt
%license LICENSES/CC-BY-4.0.txt
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc INSTALL.md
%doc README.md
%doc SECURITY.md
%doc TESTING.md
%{_bindir}/eza
%{bash_completions_dir}/eza
%{fish_completions_dir}/eza.fish
%{zsh_completions_dir}/_eza

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
install -Dpm 0644 completions/bash/eza -t %{buildroot}%{bash_completions_dir}
install -Dpm 0644 completions/fish/eza.fish -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 completions/zsh/_eza -t %{buildroot}%{zsh_completions_dir}


%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
