# Generated by rust2rpm 27
# * Doesn't compile for testutils
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

%global crate sccache

Name:           rust-sccache
Version:        0.10.0
Release:        %autorelease
Summary:        Ccache-like tool

License:        Apache-2.0
URL:            https://crates.io/crates/sccache
Source:         %{crates_source}
Source:         sccache-0.10.0-vendor.tar.xz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          sccache-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(zlib)

%global _description %{expand:
Sccache is a ccache-like tool. It is used as a compiler wrapper and
avoids compilation when possible. Sccache has the capability to utilize
caching in remote storage environments, including various cloud storage
options, or alternatively, in local storage.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CODE_OF_CONDUCT.md
%doc README.md
%{_bindir}/sccache
%{_bindir}/sccache-dist

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build -f dist-server,native-zlib
%{cargo_license_summary -f dist-server,native-zlib}
%{cargo_license -f dist-server,native-zlib} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install -f dist-server,native-zlib

%if %{with check}
%check
%cargo_test -f dist-server,native-zlib
%endif

%changelog
%autochangelog
