# Generated by rust2rpm 27
# * Doesn't compile for testutils
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

%global crate cargo-edit

Name:           rust-cargo-edit
Version:        0.13.4
Release:        %autorelease
Summary:        Cargo commands for modifying a Cargo.toml file.

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/cargo-edit
Source:         %{crates_source}
Source:         cargo-edit-0.13.4-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Cargo commands for modifying a `Cargo.toml` file..}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/cargo-add
%{_bindir}/cargo-rm
%{_bindir}/cargo-set-version
%{_bindir}/cargo-upgrade

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
