# Generated by rust2rpm 27
# * Doesn't compile for testutils
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

%global crate starship

Name:           rust-starship
Version:        1.22.1
Release:        %autorelease
Summary:        Minimal, blazing-fast, and infinitely customizable prompt for any shell! ☄🌌️

License:        ISC
URL:            https://crates.io/crates/starship
Source:         %{crates_source}
Source:         starship-1.22.1-vendor.tar.xz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          starship-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake

%global _description %{expand:
The minimal, blazing-fast, and infinitely customizable prompt for any
shell! ☄🌌️.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/starship
%{_datadir}/fish/vendor_completions.d/starship.fish

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
mkdir -p $RPM_BUILD_ROOT/%{_datadir}/fish/vendor_completions.d
$RPM_BUILD_ROOT/%{_bindir}/starship completions fish > $RPM_BUILD_ROOT/%{_datadir}/fish/vendor_completions.d/starship.fish


%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
