# Generated by rust2rpm 27
# * Doesn't compile for testutils
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

%global crate atuin

Name:           rust-atuin
Version:        18.4.0
Release:        %autorelease
Summary:        - magical shell history

License:        MIT
URL:            https://crates.io/crates/atuin
Source:         %{crates_source}
Source:         atuin-18.4.0-vendor.tar.xz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          atuin-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Atuin - magical shell history.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/atuin

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor
find ./vendor -type f -executable -name '*.rs' -exec chmod -x '{}' \;


%build
%cargo_build -n
%{cargo_license_summary -n}
%{cargo_license -n} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install -n


%if %{with check}
%check
%cargo_test -n
%endif

%changelog
%autochangelog
