# Generated by go2rpm 1.16.0
%bcond check 1

# https://github.com/astarte-platform/astartectl
%global goipath         github.com/astarte-platform/astartectl
Version:                24.5.2

%gometa -L -f

%global common_description %{expand:
Astarte command line client utility.}

Name:           golang-astartectl
Release:        %autorelease
Summary:        Astarte command line client utility

# Generated by go-vendor-tools
License:        TODO: %{warn:Please fill in the License tag!}
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description %{common_description}

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/astartectl %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gocheck
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc CHANGELOG.md README.md
%{_bindir}/astartectl


%changelog
%autochangelog
