name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash
jobs:
  release-please:
    runs-on: ubuntu-24.04
    outputs:
      release: ${{ toJson(steps.release.outputs) }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
  release-rpm:
    name: run ${{ matrix.rpm.name }} release
    needs: [release-please]
    strategy:
      matrix:
        rpm:
          - name: astartectl
            package: golang-astartectl
          - name: atuin
            package: rust-atuin
          - name: cargo-nextest
            package: rust-cargo-nextest
          - name: jj-cli
            package: rust-jj-cli
          - name: sccache
            package: rust-sccache
          - name: cargo-edit
            package: rust-cargo-edit
      fail-fast: false
    uses: ./.github/workflows/rpm-release.yaml
    secrets: inherit
    with:
      name: ${{ matrix.rpm.name }}
      package: ${{ matrix.rpm.package }}
      release: ${{ needs.release-please.outputs.release }}
