name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash
jobs:
  release-please:
    runs-on: ubuntu-24.04
    outputs:
      release: ${{ toJson(steps.release.outputs) }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
  upload-sources:
    name: upload astartectl sources
    needs: [release-please]
    uses: ./.github/workflows/rpm-astartectl-release.yaml
    secrets: inherit
    if: ${{ fromJSON(needs.release-please.outputs.release)['rpm/astartectl--release_created'] }}
    with:
      tag: ${{ fromJson(needs.release-please.outputs.release)['rpm/astartectl--tag_name'] }}
