name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash
jobs:
  release-please:
    runs-on: ubuntu-24.04
    outputs:
      release: ${{ toJson(steps.release.outputs) }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
  release-astartectl:
    name: run astartectl release
    needs: [release-please]
    uses: ./.github/workflows/rpm-astartectl-release.yaml
    secrets: inherit
    permissions:
      contents: write
    if: ${{ fromJSON(needs.release-please.outputs.release)['rpm/astartectl--release_created'] }}
    with:
      tag: ${{ fromJson(needs.release-please.outputs.release)['rpm/astartectl--tag_name'] }}
  release-cargo-nextest:
    name: run cargo-nextest release
    needs: [release-please]
    uses: ./.github/workflows/rpm-cargo-nextest-release.yaml
    secrets: inherit
    permissions:
      contents: write
    if: ${{ fromJSON(needs.release-please.outputs.release)['rpm/cargo-nextest--release_created'] }}
    with:
      tag: ${{ fromJson(needs.release-please.outputs.release)['rpm/cargo-nextest--tag_name'] }}
  release-atuin:
    name: run atuin release
    needs: [release-please]
    uses: ./.github/workflows/rpm-atuin-release.yaml
    secrets: inherit
    permissions:
      contents: write
    if: ${{ fromJSON(needs.release-please.outputs.release)['rpm/atuin--release_created'] }}
    with:
      tag: ${{ fromJson(needs.release-please.outputs.release)['rpm/atuin--tag_name'] }}
  release-jj-cli:
    name: run jj-cli release
    needs: [release-please]
    uses: ./.github/workflows/rpm-jj-cli-release.yaml
    secrets: inherit
    permissions:
      contents: write
    if: ${{ fromJSON(needs.release-please.outputs.release)['rpm/jj-cli--release_created'] }}
    with:
      tag: ${{ fromJson(needs.release-please.outputs.release)['rpm/jj-cli--tag_name'] }}
  release-sccache:
    name: run sccache release
    needs: [release-please]
    uses: ./.github/workflows/rpm-sccache-release.yaml
    secrets: inherit
    permissions:
      contents: write
    if: ${{ fromJSON(needs.release-please.outputs.release)['rpm/sccache--release_created'] }}
    with:
      tag: ${{ fromJson(needs.release-please.outputs.release)['rpm/sccache--tag_name'] }}
