name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
defaults:
  run:
    shell: bash
jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
