name: rpm-cargo-nextest-release
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: Tag to push the sources to
        required: true
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to push the sources to
        required: true
permissions:
  contents: write
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  create-sources:
    runs-on: ubuntu-24.04
    container:
      image: fedora:41
    steps:
      - name: install dependencies
        run: |
          dnf install -y fedora-packager git make
      - uses: actions/checkout@v4
      # BUG: fixes permission in github actions container
      - name: set safe git directory
        run: |
          git config --system --add safe.directory "$PWD"
      - run: |
          cd rpm/cargo-nextest
          make install-deps
      - name: build the rpm
        run: |
          rpmdev-setuptree
          cd rpm/cargo-nextest
          make build
          CHANGED="$(git status -u --porcelain)"
          if [[ -n "$CHANGED" ]]; then
            git diff
            echo "file changed"
            exit 1
          fi
      - name: call webhook
        env:
          WEBHOOK: ${{ secrets.COPR_WEBHOOK }}
        run: |
          curl -X POST "$WEBHOOK/rust-cargo-nextest"
