name: rpm-astartectl-build
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/rpm-astartectl-build.yaml"
      - "rpm/astartectl/Makefile"
      - "rpm/astartectl/go-vendor-tools.toml"
      - "rpm/astartectl/golang-astartectl.spec"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rpm-astartectl-build.yaml"
      - "rpm/astartectl/Makefile"
      - "rpm/astartectl/go-vendor-tools.toml"
      - "rpm/astartectl/golang-astartectl.spec"
permissions:
  contents: read
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  build:
    uses: ./.github/workflows/rpm-build.yaml
    secrets: inherit
    with:
      name: astartectl
