name: rpm-astartectl-build
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "rpm/astartectl/**"
  push:
    branches:
      - main
    paths:
      - "rpm/astartectl/**"
permissions:
  contents: read
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: fedora:41
    steps:
      - name: install dependencies
        run: |
          dnf install -y fedora-packager git rpmlint go2rpm
      - uses: actions/checkout@v4
        with:
          set-safe-directory: true
      # BUG: fixes permission in github actions container
      - name: set safe git directory
        run: |
          git config --system --add safe.directory "$PWD"
      - name: build the rpm
        run: |
          rpmdev-setuptree
          cd rpm/astartectl
          ./generate.sh
          CHANGED="$(git status -u --porcelain)"
          if [[ -n "$CHANGED" ]]; then
            git diff
            echo "file changed"
            exit 1
          fi
          ./build.sh
