name: rpm-atuin-build
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/rpm-atuin-build.yaml"
      - "rpm/atuin/Makefile"
      - "rpm/atuin/rust2rpm.toml"
      - "rpm/atuin/rust-atuin.spec"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rpm-atuin-build.yaml"
      - "rpm/atuin/Makefile"
      - "rpm/atuin/rust2rpm.toml"
      - "rpm/atuin/rust-atuin.spec"
permissions:
  contents: read
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  build:
    uses: ./.github/workflows/rpm-build.yaml
    secrets: inherit
    with:
      name: atuin
